config/routes.rb
ElephantWebApp::Application.routes.draw do


    root to: 'static_pages#home'

    match '/help', to: 'static_pages#help'
    match '/features', to: 'static_pages#features'
    match '/about', to: 'static_pages#about'
    match '/sales', to: 'static_pages#sales'
    match '/overview', to: 'overview#overview', :via => :get
    match '/insight', to: 'explore#index', :via => :get
    match '/overview', to: 'overview#filter_overview', :via => :post
    match '/terms_of_use', to: 'static_pages#terms_of_use'
    match '/tutorial', to: 'static_pages#tutorial'
    match '/terms', to: 'static_pages#terms'
    match '/privacy', to: 'static_pages#privacy'
    match '/copyright', to: 'static_pages#copyright'

    match '/pusher/auth', to: 'pusher#auth'

    resources :users, only: [:index, :show, :new, :create, :destroy, :edit, :update]

    resources :user_roles, only: [:index, :show, :new, :create, :destroy, :edit, :update]

    resources :sessions, only: [:create, :destroy]

    #match "/settings" => "settings#edit", :via => :get
    #match "/settings" => "settings#update", :via => :put
    resources :settings, only: [:edit, :update, :security, :update_security]
    match '/security', to: 'settings#security'
    match '/update_security', to: 'settings#update_security'

    match '/signin', to: 'sessions#new'
    match '/is_signed_in', to: 'sessions#show'
    get '/update_password', to: 'sessions#edit'
    match '/create_password', to: 'sessions#update', via: :post
    match '/signout', to: 'sessions#destroy', via: :delete
    match '/reset_password', to: 'sessions#reset_password'
    match '/verify_network', to: 'sessions#verify_network'

    resources :elephant_admin, only: [:index]
    match '/elephant_admin', to: 'elephant_admin#index'

    resources :companies, only: [:new, :destroy, :create, :show, :edit, :update]

    resources :job_templates, only: [:index, :new, :create, :destroy, :show, :edit, :update]

    resources :clients, only: [:index, :new, :create, :destroy, :show, :edit, :update]

    resources :districts, only: [:index, :new, :create, :destroy, :show, :edit, :update]

    resources :countries, only: [:show]

    resources :divisions, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :segments, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :product_lines, only: [:index, :show, :new, :create, :edit, :update, :destroy]

    resources :documents, only: [:show, :new, :create, :update, :destroy]

    resources :dynamic_fields, only: [:index, :show, :new, :create, :edit, :update, :destroy]

    resources :activities, only: [:index, :show]



    resources :jobs, only: [:index, :show, :new, :create, :update, :destroy]

    resources :fields, only: [:index, :show, :new, :create]

    resources :wells, only: [:index, :show, :new, :create, :edit, :update]
    resources :rigs, only: [:index, :new, :create, :show]



    resources :search, only: [:new, :create, :index]

    resources :history, only: [:index]
    resources :insight, only: [:index]

    resources :alerts, only: [:index]


    resources :job_notes, only: [:new, :create, :destroy]

    resources :job_memberships, only: [:new, :edit, :update, :create, :destroy]

    resources :job_note_comments, only: [:create, :destroy]

    resources :conversations, only: [:index, :show, :new, :create, :destroy, :update]

    resources :tools, only: [:new, :create, :edit, :update, :destroy]
    resources :primary_tools, only: [:index, :create, :destroy, :show, :update]
    resources :secondary_tools, only: [:index, :new, :create, :update, :destroy]

    resources :failures, only: [:index, :new, :show, :create, :edit, :update, :destroy]

    resources :post_job_report_documents, only: [:create, :update, :destroy]

    resources :document_shares, only: [:index, :show, :new, :create, :update, :destroy]


    # Inventory
    resources :inventory, only: [:index, :show]
    resources :parts, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy]
    resources :suppliers, only: [:show, :new, :create, :edit, :update, :destroy]
    resources :warehouse_memberships, only: [:new, :edit, :update, :create, :destroy]

    resources :part_memberships, only: [:new, :create, :edit, :update, :destroy]


    resources :job_logs, only: [:index, :create, :show]
    resources :drilling_logs, only: [:index, :show]
    resources :drilling_log_entries, only: [:show, :new, :create, :show, :edit, :update, :destroy]

    resources :job_times, only: [:index, :update]


    resources :bhas, only: [:show, :new, :create, :edit, :update, :destroy]

    resources :issues, only: [:index, :show, :create, :edit, :update, :destroy]

    resources :surveys, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources :survey_points, only: [:new, :create, :edit, :update, :destroy]

    resources :rig_memberships, only: [:new, :create, :destroy]

    resources :shipments, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :shippers, only: [:index, :show, :new, :create, :edit, :update, :destroy]

    resources :asset_lists, only: [:index, :show]
    resources :asset_list_entries, only: [:show, :new, :create, :edit, :update, :destroy]

    resources :job_costs, only: [:index, :show, :new, :create, :edit, :update, :destroy]

    match '/report_status/:id', to: 'reports#status', :via => :get

    resources :survey_projections, only: [:new, :create]

end

app/controllers/part_memberships_controller.rb
class PartMembershipsController < ApplicationController
    before_filter :signed_in_user, only: [:new, :create, :edit, :update, :destroy]

    def new
        @part_membership = PartMembership.new
    end

    def create
        if params[:part_membership][:job_id].present?
            job_id = params[:part_membership][:job_id]
            params[:part_membership].delete(:job_id)
        else
            shipment_id = params[:part_membership][:shipment_id]
            params[:part_membership].delete(:shipment_id)
        end

        from_type = params[:part_membership][:from_type]
        params[:part_membership].delete(:from_type)

        to_type = params[:part_membership][:to_type]
        params[:part_membership].delete(:to_type)

        part_id = params[:part_membership][:part_id]
        params[:part_membership].delete(:part_id)

        part_type = params[:part_membership][:part_type]
        params[:part_membership].delete(:part_type)

        price = params[:part_membership][:price]
        params[:part_membership].delete(:price)

        @part_membership = PartMembership.new(params[:part_membership])
        @part_membership.company = current_user.company
        @part_membership.price = price.to_s.gsub(/,/, '').to_f

        case part_type
            when 'inventory'
                @part_membership.part_type = PartMembership::INVENTORY
            when 'rental'
                @part_membership.part_type = PartMembership::RENTAL
                @part_membership.name = params["rental_name"]
                @part_membership.serial_number = params["rental_serial_number"]
                @part_membership.asset_type = params["rental_asset_type"]

                part = Part.new
                part.company = current_user.company
                part.template = false
                part.rental = true
                if params["rental_district_id"].present?
                    part.district = District.find_by_id(params["rental_district_id"])
                elsif !shipment_id.blank?
                    part.district = Shipment.find_by_id(shipment_id).district
                elsif !job_id.blank?
                    part.district = Job.find_by_id(job_id).district
                end
                part.asset_type = @part_membership.asset_type
                part.manufacturer = params["rental_manufacturer"]
                part.name = params["rental_name"]
                part.serial_number = params["rental_serial_number"]
                part.save
                @part_membership.part = part

            when 'accessory'
                @part_membership.part_type = PartMembership::SALEABLE
                @part_membership.name = params["accessory_name"]
                @part_membership.serial_number = params["accessory_serial_number"]
                @part_membership.asset_type = params["accessory_asset_type"]
        end

        case from_type
            when Warehouse.name
                @part_membership.from = Warehouse.find_by_id(params[:from_id_warehouse])
                @part_membership.from_name = @part_membership.from.present? ? @part_membership.from.name : ""
            when Supplier.name
                @part_membership.from = Supplier.find_by_id(params[:from_id_supplier])
                @part_membership.from_name = @part_membership.from.present? ? @part_membership.from.name : ""
                if @part_membership.part.present? && @part_membership.part.rental
                    @part_membership.part.supplier = @part_membership.from
                    @part_membership.part.save
                end
            when Job.name
                @part_membership.from = Job.find_by_id(params[:from_id_job])
                @part_membership.from_name = @part_membership.from.present? ? (@part_membership.from.well.rig.present? ? @part_membership.from.well.rig.name + " - " : "") + @part_membership.from.field.name + " | " + @part_membership.from.well.name : ""
        end

        case to_type
            when Warehouse.name
                @part_membership.to = Warehouse.find_by_id(params[:to_id_warehouse])
                @part_membership.to_name = @part_membership.to.present? ? @part_membership.to.name : ""
            when Supplier.name
                @part_membership.to = Supplier.find_by_id(params[:to_id_supplier])
                @part_membership.to_name = @part_membership.to.present? ? @part_membership.to.name : ""
            when Job.name
                @part_membership.to = Job.find_by_id(params[:to_id_job])
                @part_membership.to_name = @part_membership.to.present? ? (@part_membership.to.well.rig.present? ? @part_membership.to.well.rig.name + " - " : "") + @part_membership.to.field.name + " | " + @part_membership.to.well.name : ""
        end

        @part_membership.inner_diameter = BigDecimal(params[:id])
        @part_membership.outer_diameter = BigDecimal(params[:od])
        @part_membership.length = BigDecimal(params[:length])
        @part_membership.up = params[:up].to_i
        @part_membership.down = params[:down].to_i


        if !job_id.blank?
            @part_membership.job = Job.find_by_id(job_id)
            not_found unless @part_membership.job.present? && @part_membership.job.company == current_user.company
        else
            @part_membership.shipment = Shipment.find_by_id(shipment_id)
            if @part_membership.shipment.present? && @part_membership.shipment.from_type == Supplier.name
                @part_membership.part.supplier = @part_membership.shipment.from
            end
        end

        if !part_id.blank? && @part_membership.part_type == PartMembership::INVENTORY
            @part_membership.part = Part.find_by_id(part_id)
            not_found unless @part_membership.part.present?
            not_found unless @part_membership.part.company == current_user.company
            @part_membership.name = @part_membership.part.master_part.name
            @part_membership.material_number = @part_membership.part.material_number
            @part_membership.serial_number = @part_membership.part.serial_number

            # For Inventory parts
            if @part_membership.job.present?
                @part_membership.part.asset_on_job @part_membership.job
            elsif @part_membership.shipment.present?
                @part_membership.part.asset_shipping @part_membership.shipment
            end
        end

        # For Rental parts
        if @part_membership.part.present? && @part_membership.part_type == PartMembership::RENTAL
            if @part_membership.job.present?
                @part_membership.part.asset_on_job @part_membership.job
            elsif @part_membership.shipment.present?
                @part_membership.part.asset_shipping @part_membership.shipment
            end
        end

        if @part_membership.save
            if @part_membership.job.present?
                if @part_membership.part.present?
                    AssetActivity.delay.add(current_user, AssetActivity::ADDED_TO_JOB, @part_membership.part, @part_membership.job)
                    Activity.delay.add(current_user, Activity::ASSET_ADDED, @part_membership.part, @part_membership.part.serial_number, @part_membership.job)
                else
                    Activity.delay.add(current_user, Activity::ASSET_ADDED, nil, @part_membership.serial_number, @part_membership.job)
                end
            elsif @part_membership.shipment.present?
                AssetActivity.delay.add(current_user, AssetActivity::ADDED_TO_SHIPMENT, @part_membership.part, @part_membership.shipment)
            end
        end
    end

    def edit
        @part_membership = PartMembership.find_by_id(params[:id])
    end

    def update
        @part_membership = PartMembership.find_by_id(params[:id])

        if params[:usage].present?
            @part_membership.update_attribute(:usage, Float(params[:usage]))
        elsif params[:part_membership].present?
            @part_membership.update_attributes(params[:part_membership])
        end
    end

    def destroy
        @part_membership = PartMembership.find_by_id(params[:id])
        not_found unless @part_membership.present?

        PartMembership.transaction do
            if @part_membership.destroy
                if @part_membership.job.present?
                    if @part_membership.part.present?
                        @part_membership.part.removed true
                        AssetActivity.delay.add(current_user, AssetActivity::DELETED_FROM_JOB, @part_membership.part, @part_membership.job)
                        Activity.delay.add(current_user, Activity::ASSET_REMOVED, @part_membership.part, @part_membership.part.serial_number, @part_membership.job)
                    else
                        Activity.delay.add(current_user, Activity::ASSET_REMOVED, nil, @part_membership.serial_number, @part_membership.job)
                    end
                elsif @part_membership.shipment.present? && @part_membership.part.present?
                    if @part_membership.part.rental
                        @part_membership.part.destroy
                    else
                        AssetActivity.delay.add(current_user, AssetActivity::DELETED_FROM_SHIPMENT, @part_membership.part, @part_membership.shipment)
                        @part_membership.part.removed false
                    end
                end
            end
        end
    end

end

app/views/part_memberships/_edit_part_membership.html.erb
<div class="section-header">
  <h1>Edit Asset</h1>
</div>

<div class="ajax-form">
  <br>

  <%= form_for part_membership, remote: true do |f| %>

      <div class=''>
        <div class='inline-block'>
          <b>ID</b>
          <%= f.text_field :inner_diameter,
                           placeholder: "ID",
                           class: "txtfield bha-value id-od tooltip-info",
                           "data-placement" => "bottom",
                           "data-title" => "ID (Inner Diameter) of Asset" %>
        </div>
        <div class='inline-block push-right-small'>
          <b>OD</b>
          <%= f.text_field :outer_diameter,
                           placeholder: "OD",
                           class: "txtfield bha-value id-od tooltip-info",
                           "data-placement" => "bottom",
                           "data-title" => "OD (Outer Diameter) of Asset" %>
        </div>

        <div class='inline-block push-right-small'>
          <b>Length</b>
          <%= f.text_field :length,
                           placeholder: "Length",
                           class: "txtfield bha-value id-od tooltip-info",
                           "data-placement" => "bottom",
                           "data-title" => "Length of Asset" %>
        </div>
      </div>
      <div class="content actions">
        <%= f.submit "Update Asset", class: "btn btn-success pull-right" %>
      </div>
  <% end %>
</div>

<div class="ajax-loading center hidden">
  <br>
  <br>
  <span class="ajax-loading search-loading"><b>Saving asset...</b></span>
  <br>
</div>

app/views/part_memberships/_new.html.erb
<div class='add-new-asset'>
  <div class='form' data-form="new-asset-form">
    <%= form_for PartMembership.new, remote: true do |f| %>

        <% if shipment.present? %>
            <%= f.hidden_field :shipment_id, value: shipment.id %>
        <% else %>
            <%= f.hidden_field :job_id, value: @job.id %>
        <% end %>
        <%= f.hidden_field :part_type, id: "part_type", value: "inventory" %>

        <div class='push-down'>
          <ul class="nav nav-pills selection-nav">
            <% if allow_inventory %>
                <li class='active'>
                  <a href="#" class='change-asset-type' data-type="inventory">Owned Asset</a>
                </li>
            <% end %>
            <li class=" <%= !allow_inventory ? " " : "push-right-small" %>">
              <a href="#" id="rental_tab" class='change-asset-type blue-text' data-type="rental">Rental</a>
            </li>
            <li class="push-right-small">
              <a href="#" id="accessory_tab" class='change-asset-type blue-text' data-type="accessory">Saleable</a>
            </li>
          </ul>
        </div>

        <div style='border-style: dashed; border-width: 0px; border-bottom-width: 1px; height: 1px; border-color: #666; margin-top: -8px; margin-bottom: 10px;'></div>

        <div class='inline-block asset-type-form align-top' data-type="inventory">
          <%= f.hidden_field :part_id %>
          <%= text_field_tag "", "", data: {autocomplete_source: parts_path(district_id: shipment.present? ? shipment.district_id : @job.district.id, show_master: false)},
                             placeholder: "Find by Serial #, Material #, or Name",
                             class: "txtfield search-query tooltip-info part-search txtfield-long align-top",
                             id: "part_search",
                             "data-placement" => "bottom",
                             "data-title" => "Asset Serial #, Material #, or Name" %>

        </div>

        <div class='inline-block asset-type-form align-top hidden' data-type="rental">
          <%= text_field_tag "rental_manufacturer", "",
                             placeholder: "Manufacturer",
                             class: "txtfield asset-input  tooltip-info align-top",
                             "data-placement" => "bottom",
                             "data-title" => "Manufacturer Name" %>

          <%= text_field_tag "rental_name", "",
                             placeholder: "Asset Name",
                             class: "txtfield asset-input  tooltip-info align-top",
                             "data-placement" => "bottom",
                             "data-title" => "Asset Name" %>

          <%= text_field_tag "rental_serial_number", "",
                             placeholder: "Serial Number",
                             class: "txtfield asset-input  tooltip-info align-top",
                             "data-placement" => "bottom",
                             "data-title" => "Serial Number" %>

          <%= hidden_field_tag "rental_district_id", shipment.present? ? shipment.district_id : @job.district.id %>

          <div class="inline-block tooltip-info align-top push-down-small"
               data-title="Tool Type">
            <%= image_tag "tool.png", class: "inline-block push-down-small" %>
            <%= select_tag "rental_asset_type",
                           options_for_select(BhaItem.type_options),
                           class: "custom-select-ajax bha-value2 align-top",
                           placeholder: "Type" %>
          </div>

        </div>


        <div class='inline-block asset-type-form align-top hidden' data-type="accessory">
          <%= text_field_tag "accessory_name", "",
                             placeholder: "Asset Name",
                             class: "txtfield asset-input  tooltip-info align-top",
                             "data-placement" => "bottom",
                             "data-title" => "Asset Name" %>

          <%= text_field_tag "accessory_serial_number", "",
                             placeholder: "Serial Number",
                             class: "txtfield asset-input  tooltip-info align-top",
                             "data-placement" => "bottom",
                             "data-title" => "Serial Number" %>

          <div class="inline-block tooltip-info align-top push-down-small"
               data-title="Tool Type">
            <%= image_tag "tool.png", class: "inline-block push-down-small" %>
            <%= select_tag "accessory_asset_type",
                           options_for_select(BhaItem.type_options),
                           class: "custom-select-ajax bha-value2 align-top",
                           placeholder: "Type" %>
          </div>

        </div>

        <br>

        <%= f.submit "+ Add Asset", class: "btn btn-primary inline-block pull-right  tooltip-info form-loading-on-click",
                     "data-form" => "new-asset-form",
                     "data-placement" => "bottom",
                     "data-title" => "Add new asset" do %>
            <% end %>

        <div class='push-down'>

          <div class='inline-block id-od-box'>
            <p class='inline-block' style='font-size: 9px; vertical-align: top; margin-left:3px;'>ID</p>
            <%= text_field_tag "id", "",
                               placeholder: "ID",
                               class: "txtfield bha-value id-od tooltip-info",
                               "data-placement" => "bottom",
                               "data-title" => "ID (Inner Diameter) of Asset" %>
            <p class='inline-block' style='font-size: 9px; vertical-align: top;'>OD</p>
            <%= text_field_tag "od", "",
                               placeholder: "OD",
                               class: "txtfield bha-value id-od tooltip-info",
                               "data-placement" => "bottom",
                               "data-title" => "OD (Outer Diameter) of Asset" %>
            <%= text_field_tag "length", "",
                               placeholder: "Length",
                               class: "txtfield bha-value id-od tooltip-info",
                               "data-placement" => "bottom",
                               "data-title" => "Length of Asset" %>
          </div>

          <div class="inline-block push-right-small tooltip-info" data-title="Upward connection">
            <b><i class="icon-arrow-up"></i></b>
            <%= select_tag "up", options_for_select(BhaItem.options),
                           class: "custom-select-ajax bha-value2 align-top push-up",
                           placeholder: "Up" %>
          </div>

          <div class="inline-block push-right-small push-down tooltip-info" data-title="Downward connection">
            <b><i class="icon-arrow-down"></i></b>
            <%= select_tag "down", options_for_select(BhaItem.options),
                           class: "custom-select-ajax bha-value2 align-top push-up",
                           placeholder: "Down" %>
          </div>

          <div>
            <div style='width: 100px; margin-top: 10px;'>
              <b class='orange-text'>Cost</b>
            </div>

            <div class="inline-block align-top">
              <%= f.select :charge_type, options_for_select([["Day", JobCost::DAY], ["Job", JobCost::JOB], ["Hour", JobCost::HOUR], ["Item", JobCost::ITEM]]),
                           {},
                           style: "margin-right: 10px;",
                           class: "custom-select custom-select-ajax align-top",
                           placeholder: "Up" %>
            </div>

            <%= f.text_field :price, placeholder: "$0.00",
                             value: nil,
                             class: "txtfield tooltip-info align-top",
                             style: "width: 100px !important; min-width: 0px;",
                             "data-placement" => "bottom",
                             "data-title" => "Price" %>
          </div>
        </div>



    <% end %>
  </div>

  <div class="form-loading hidden" data-form="new-asset-form">
    <%= render 'layouts/inline_loading', title: "Adding asset..." %>
    <br><br>
  </div>
  <hr>
</div>

<% if !allow_inventory %>
    <script type='text/javascript'>
        $('#rental_tab').trigger('click');
    </script>
<% end %>

app/views/part_memberships/_part_membership.html.erb
<div id="part_membership_<%= part_membership.id %>"
     class="inline-block align-top part-membership"
     data-shipping="<%= part_membership.shipping? ? "true" : "false" %>">
  <% if current_user.role.access_to_inventory? %>
      <%= link_to part_membership.part.present? ? part_membership.part : part_membership.job.present? ? job_path(part_membership.job, anchor: 'assets') : jobs_path,
                  class: "part-box2 popover " + (part_membership.part_type == PartMembership::ACCESSORY ? "part-box-accessory" : "") + ' ' + (@make_green.present? && @make_green ? 'green' : ''),
                  "data-html" => "true",
                  "data-title" => (part_membership.part.present? && part_membership.part.master_part.present? ? part_membership.part.master_part.name : part_membership.name),
                  "data-content" => render('part_memberships/part_hover', part_membership: part_membership, allow_remove: allow_remove),
                  "data-toggle" => "popover",
                  "data-placement" => "bottom",
                  "data-trigger" => "hover" do %>
          <div class='bar' style="background: <%= '#' + part_membership.color %>;"></div>
          <% if part_membership.part_type == PartMembership::RENTAL %>
              <div class='rental'>R</div>
          <% end %>
          <% if part_membership.part_type == PartMembership::SALEABLE %>
              <div class='accessory'>S</div>
          <% end %>
          <div class='center name'><%= part_membership.part.present? && part_membership.part.master_part.present? ? part_membership.part.master_part.name : part_membership.name %></div>
          <div class='center'><%= part_membership.serial_number %></div>
      <% end %>
  <% else %>
      <%= div_for part_membership,
                  class: "part-box2 popover " + (part_membership.part_type == PartMembership::ACCESSORY ? "part-box-accessory" : ""),
                  "data-html" => "true",
                  "data-title" => (part_membership.part.present? && part_membership.part.master_part.present? ? part_membership.part.master_part.name : part_membership.name),
                  "data-content" => render('part_memberships/part_hover', part_membership: part_membership, allow_remove: allow_remove),
                  "data-toggle" => "popover",
                  "data-placement" => "bottom",
                  "data-trigger" => "hover" do %>
          <div class='bar' style="background: <%= '#' + part_membership.color %>;"></div>
          <% if part_membership.part_type == PartMembership::RENTAL %>
              <div class='rental'>R</div>
          <% end %>
          <% if part_membership.part_type == PartMembership::SALEABLE %>
              <div class='accessory'>S</div>
          <% end %>
          <div class='center name'><%= part_membership.part.present? && part_membership.part.master_part.present? ? part_membership.part.master_part.name : part_membership.name %></div>
          <div class='center'><%= part_membership.serial_number %></div>
      <% end %>
  <% end %>
</div>

app/views/part_memberships/_part_membership_small.html.erb
<div id="part_membership_<%= part_membership.id %>"
     class="inline-block align-top part-membership"
     data-shipping="<%= part_membership.shipping? ? "true" : "false" %>">
  <% if current_user.role.access_to_inventory? %>
      <%= link_to part_membership.part.present? ? part_membership.part : part_membership.job.present? ? job_path(part_membership.job, anchor: 'assets') : jobs_path,
                  target: "_blank",
                  class: "part-box2 popover " + (part_membership.part_type == PartMembership::ACCESSORY ? "part-box-accessory" : "") + ' ' + (@make_green.present? && @make_green ? 'green' : ''),
                  style: "height: 30px; width: 130px;",
                  "data-html" => "true",
                  "data-title" => (part_membership.part.present? ? (part_membership.part.master_part.present? ? part_membership.part.master_part.name : part_membership.part.name) : part_membership.name),
                  "data-content" => render('part_memberships/part_hover', part_membership: part_membership, allow_remove: allow_remove),
                  "data-toggle" => "popover",
                  "data-placement" => "bottom",
                  "data-trigger" => "hover" do %>
          <div class='bar' style="background: <%= '#' + part_membership.color %>;"></div>
          <% if part_membership.part_type == PartMembership::RENTAL %>
              <div class='rental'>R</div>
          <% end %>
          <% if part_membership.part_type == PartMembership::ACCESSORY %>
              <div class='accessory'>DI</div>
          <% end %>
          <div class=' name' style='margin-left: 5px;'><%= (part_membership.part.present? ? (part_membership.part.master_part.present? ? part_membership.part.master_part.name : part_membership.part.name) : part_membership.name)%></div>
          <div class='' style='margin-left: 5px; margin-top: -5px;'><%= part_membership.serial_number %></div>
      <% end %>
  <% else %>
      <%= div_for part_membership,
                  class: "part-box2 popover " + (part_membership.part_type == PartMembership::ACCESSORY ? "part-box-accessory" : ""),
                  style: "height: 30px; width: 130px;",
                  "data-html" => "true",
                  "data-title" => (part_membership.part.present? ? (part_membership.part.master_part.present? ? part_membership.part.master_part.name : part_membership.part.name) : part_membership.name),
                  "data-content" => render('part_memberships/part_hover', part_membership: part_membership, allow_remove: allow_remove),
                  "data-toggle" => "popover",
                  "data-placement" => "bottom",
                  "data-trigger" => "hover" do %>
          <div class='bar' style="background: <%= '#' + part_membership.color %>;"></div>
          <% if part_membership.part_type == PartMembership::RENTAL %>
              <div class='rental'>R</div>
          <% end %>
          <% if part_membership.part_type == PartMembership::ACCESSORY %>
              <div class='accessory'>DI</div>
          <% end %>
          <div class='name' style='margin-left: 5px;'><%= (part_membership.part.present? ? (part_membership.part.master_part.present? ? part_membership.part.master_part.name : part_membership.part.name) : part_membership.name) %></div>
          <div class='' style='margin-left: 5px; margin-top: -5px;'><%= part_membership.serial_number %></div>
      <% end %>
  <% end %>
</div>

app/views/part_memberships/destroy.js.erb
$('div[id=part_membership_<%= @part_membership.id %>]').remove();