config/routes.rb
ElephantWebApp::Application.routes.draw do


    root to: 'static_pages#home'

    match '/help', to: 'static_pages#help'
    match '/features', to: 'static_pages#features'
    match '/about', to: 'static_pages#about'
    match '/sales', to: 'static_pages#sales'
    match '/overview', to: 'overview#overview', :via => :get
    match '/insight', to: 'explore#index', :via => :get
    match '/overview', to: 'overview#filter_overview', :via => :post
    match '/terms_of_use', to: 'static_pages#terms_of_use'
    match '/tutorial', to: 'static_pages#tutorial'
    match '/terms', to: 'static_pages#terms'
    match '/privacy', to: 'static_pages#privacy'
    match '/copyright', to: 'static_pages#copyright'

    match '/pusher/auth', to: 'pusher#auth'

    resources :users, only: [:index, :show, :new, :create, :destroy, :edit, :update]

    resources :user_roles, only: [:index, :show, :new, :create, :destroy, :edit, :update]

    resources :sessions, only: [:create, :destroy]

    #match "/settings" => "settings#edit", :via => :get
    #match "/settings" => "settings#update", :via => :put
    resources :settings, only: [:edit, :update, :security, :update_security]
    match '/security', to: 'settings#security'
    match '/update_security', to: 'settings#update_security'

    match '/signin', to: 'sessions#new'
    match '/is_signed_in', to: 'sessions#show'
    get '/update_password', to: 'sessions#edit'
    match '/create_password', to: 'sessions#update', via: :post
    match '/signout', to: 'sessions#destroy', via: :delete
    match '/reset_password', to: 'sessions#reset_password'
    match '/verify_network', to: 'sessions#verify_network'

    resources :elephant_admin, only: [:index]
    match '/elephant_admin', to: 'elephant_admin#index'

    resources :companies, only: [:new, :destroy, :create, :show, :edit, :update]

    resources :job_templates, only: [:index, :new, :create, :destroy, :show, :edit, :update]

    resources :clients, only: [:index, :new, :create, :destroy, :show, :edit, :update]

    resources :districts, only: [:index, :new, :create, :destroy, :show, :edit, :update]

    resources :countries, only: [:show]

    resources :divisions, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :segments, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :product_lines, only: [:index, :show, :new, :create, :edit, :update, :destroy]

    resources :documents, only: [:show, :new, :create, :update, :destroy]

    resources :dynamic_fields, only: [:index, :show, :new, :create, :edit, :update, :destroy]

    resources :activities, only: [:index, :show]



    resources :jobs, only: [:index, :show, :new, :create, :update, :destroy]

    resources :fields, only: [:index, :show, :new, :create]

    resources :wells, only: [:index, :show, :new, :create, :edit, :update]
    resources :rigs, only: [:index, :new, :create, :show]



    resources :search, only: [:new, :create, :index]

    resources :history, only: [:index]
    resources :insight, only: [:index]

    resources :alerts, only: [:index]


    resources :job_notes, only: [:new, :create, :destroy]

    resources :job_memberships, only: [:new, :edit, :update, :create, :destroy]

    resources :job_note_comments, only: [:create, :destroy]

    resources :conversations, only: [:index, :show, :new, :create, :destroy, :update]

    resources :tools, only: [:new, :create, :edit, :update, :destroy]
    resources :primary_tools, only: [:index, :create, :destroy, :show, :update]
    resources :secondary_tools, only: [:index, :new, :create, :update, :destroy]

    resources :failures, only: [:index, :new, :show, :create, :edit, :update, :destroy]

    resources :post_job_report_documents, only: [:create, :update, :destroy]

    resources :document_shares, only: [:index, :show, :new, :create, :update, :destroy]


    # Inventory
    resources :inventory, only: [:index, :show]
    resources :parts, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy]
    resources :suppliers, only: [:show, :new, :create, :edit, :update, :destroy]
    resources :warehouse_memberships, only: [:new, :edit, :update, :create, :destroy]

    resources :part_memberships, only: [:new, :create, :edit, :update, :destroy]


    resources :job_logs, only: [:index, :create, :show]
    resources :drilling_logs, only: [:index, :show]
    resources :drilling_log_entries, only: [:show, :new, :create, :show, :edit, :update, :destroy]

    resources :job_times, only: [:index, :update]


    resources :bhas, only: [:show, :new, :create, :edit, :update, :destroy]

    resources :issues, only: [:index, :show, :create, :edit, :update, :destroy]

    resources :surveys, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources :survey_points, only: [:new, :create, :edit, :update, :destroy]

    resources :rig_memberships, only: [:new, :create, :destroy]

    resources :shipments, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :shippers, only: [:index, :show, :new, :create, :edit, :update, :destroy]

    resources :asset_lists, only: [:index, :show]
    resources :asset_list_entries, only: [:show, :new, :create, :edit, :update, :destroy]

    resources :job_costs, only: [:index, :show, :new, :create, :edit, :update, :destroy]

    match '/report_status/:id', to: 'reports#status', :via => :get

    resources :survey_projections, only: [:new, :create]

end

app/models/segment.rb
class Segment < ActiveRecord::Base
  attr_accessible :name

  acts_as_tenant(:company)

  validates :name, presence: true, length: {maximum: 50}
  validates_uniqueness_of :name, :case_sensitive => false, scope: :division_id
  validates_presence_of :company
  validates_presence_of :division

  belongs_to :division
  belongs_to :company

  has_many :product_lines, dependent: :destroy, order: "name ASC"

  searchable do
      text :name, :as => :code_textp
      integer :company_id
  end

  def self.from_company(company)
      where("company_id = :company_id", company_id: company.id)
  end

  def jobs
      self.company.jobs.joins(job_template: {product_line: :segment}).where("segments.id = ?", self.id)
  end

  def active_jobs
    Job.where("jobs.company_id = ?", self.company_id).where("jobs.status >= 1 AND jobs.status < 50").includes(job_template: {product_line: :segment}).where("segments.id = ?", self.id)
  end

  def self.from_company_for_user(segment, options, user, company)
      Sunspot.search(Job) do
          with(:segment_id, segment.id)
          any_of do
              if user.role.limit_to_assigned_jobs?
                  with(:job_membership, user.id)
              elsif user.role.limit_to_district?
                  with(:district_id, user.district.id)
              elsif user.role.limit_to_product_line? && !user.product_line.nil?
                  with(:product_line_id, user.product_line.id)
              end
          end
          with(:company_id, company.id)
          order_by :created_at, :desc
          paginate :page => options[:page]
      end
  end
end

app/controllers/segments_controller.rb
class SegmentsController < ApplicationController
    before_filter :signed_in_user, only: [:index, :show]
    before_filter :signed_in_admin, only: [:new, :create, :edit, :update, :destroy]

    respond_to :js

    def index
        if params[:segment_id].present?
            @segment = Segment.find_by_id(params[:segment_id])
            not_found unless @segment.company == current_user.company
        else
            @segments = Segment.from_company(current_user.company).order("name ASC")
        end

    end

    def show

        @segment = Segment.find_by_id(params[:id])
        not_found unless @segment.present? && @segment.company == current_user.company

        @is_paged = params[:page].present?
        if @is_paged
            @jobs = UserRole.limit_jobs_scope current_user, @segment.jobs
            @jobs = Job.include_models(@jobs).reorder('').order("jobs.created_at DESC").paginate(page: params[:page], limit: 20)
        else
            @jobs = UserRole.limit_jobs_scope current_user, @segment.jobs
            @jobs = Job.include_models(@jobs).reorder('').where("(jobs.status >= 1 AND jobs.status < 50) OR (jobs.status = :status_closed AND jobs.close_date >= :close_date)", status_closed: Job::COMPLETE, close_date: (Time.now - 5.days)).
                    order("jobs.created_at DESC")
        end
    end

    def new
        @segment = Segment.new
        division = Division.find_by_id(params[:division])
        not_found unless division.company == current_user.company
        @segment.division = division
    end

    def create
        division = Division.find_by_id(params[:segment][:division_id])
        not_found unless division.company == current_user.company
        params[:segment].delete(:division_id)

        @segment = Segment.new(params[:segment])
        @segment.division = division
        @segment.company = current_user.company

        if @segment.save

            #Activity.add(self.current_user, Activity::PRODUCT_LINE_CREATED, @product_line, @product_line.name)

            flash[:success] = "Segment created - #{@segment.name}"
            #redirect_to job_template_path_path
        else
            render 'error'
        end
    end

    def edit
        @segment = Segment.find(params[:id])
        not_found unless @segment.company == current_user.company
    end

    def update

        @segment = Segment.find(params[:id])
        not_found unless @segment.company == current_user.company

        if @segment.update_attributes(params[:segment])

            #Activity.add(self.current_user, Activity::PRODUCT_LINE_UPDATED, @product_line, @product_line.name)

            flash[:success] = "Segment updated"
            #redirect_to job_templates_path
        else
            render 'edit'
        end
    end

    def destroy
        @segment = Segment.find(params[:id])
        not_found unless @segment.company == current_user.company

        if current_user.company.jobs.includes(job_template: {product_line: :segment}).where("segments.id = ?", @segment.id).any?
            render 'job_templates/elephant_destroy'
            return
        else
            @segment.destroy
            #Activity.add(self.current_user, Activity::PRODUCT_LINE_DESTROYED, @product_line, @product_line.name)
            flash[:success] = "Segment deleted"
        end
    end
end

app/views/segments/_edit_form.html.erb
<%= form_for @segment, html: { class: "inline" }, remote: true do |f| %>

    <div id="fieldset inline">
      <div class="field inline">
        <%= f.text_field :name, placeholder: "Division Name", value: @segment.name,
                         class: "txtfield", autofocus: true %>
        <%= f.submit "Save", class: "bluebtn btnsmall" %>
        <%= link_to "Cancel", "#", class: "bluebtn btnsmall red", id: "cancel_rename_" + @segment.id.to_s %>
      </div>
    </div>


<% end %>

app/views/segments/_form.html.erb
<%= form_for @segment, html: { id: "new_segment_id_" + @segment.division.id.to_s, class: "content new-product-line push-right" }, remote: true do |f| %>

    <div class="new-product-line">
        <%=  f.hidden_field :division_id, value: @segment.division.id %>
        <%= f.text_field :name, placeholder: "New Segment Name", class: "txtfield", autofocus: true %>
        <%= f.submit "Add", class: "bluebtn btnsmall" %>

      <%= link_to "Cancel", "#", id: "cancel_segment_" + @segment.division.id.to_s, class: "bluebtn btnsmall red" %>

    </div>

<% end %>

app/views/segments/_segment.html.erb
<div id="segment_<%= segment.id %>" class="div-expand-root">


  <div class="header product-line">

    <a href="#" class="div-expand-toggle div-toggle-button tooltip-info"
       data-placement="bottom"
       data-title="Click to expand/collapse product lines">


      <span class="product-line-header"><%= segment.name %><span class="division-level-name">Segment</span></span>

    </a>


  </div>

  <div id="product_lines_<%= segment.id %>"
       class="div-toggle-content indent-content-container <%= params[:segment] != segment.id.to_s ? "hidden" : "" %>">

    <div class="indent-content">
      <%= render segment.product_lines %>
    </div>

    <%= link_to "Add Product Line", new_product_line_path(segment: segment),
                remote: true,
                class: "add-button tooltip-info",
                id: "new_product_line_link_" + segment.id.to_s,
                "data-placement" => "bottom",
                "data-title" => "Create new product line on " + segment.name %>


    <div class="inline dropdown pull-right">
      <br>
      <a href="#" class="activity-user-link dropdown-toggle tooltip-info push-right-small"
         data-placement="bottom"
         data-title="Click to rename/delete segment"
         data-toggle="dropdown"
         id="segment_<%= segment.id %>_header">Rename/Delete Segment
      </a>

      <ul class="dropdown-menu" role="menu">
        <li><%= link_to "Rename", edit_segment_path(segment), remote: true %></li>
        <li><%= link_to "Delete", segment, method: :delete, remote: true, data: {confirm: "Permanently Delete Segment? This can't be undone. This will cause all sub Product Lines, and Job Types to also be deleted. "} %></li>
      </ul>
    </div>

  </div>

</div>

app/views/segments/create.js.erb
<% if @segment.new_record? %>
$('#alert').remove();
$('body').append("<%= j render 'layouts/modal_error', title: "Problem Adding Segment", message: @segment.errors.full_messages.join(', ').html_safe %>");
$('#alert').modal({show:true});

<% else %>

$('#new_segment_id_<%= @segment.division.id %>').remove();
$('#new_segment_link_<%= @segment.division.id %>').show();

$('#segments_<%= @segment.division.id %>').find('.indent-content:first').append($("<%= j render @segment %>"));

$('#product_lines_<%= @segment.id.to_s %>').removeClass("hidden");

<% end %>

app/views/segments/destroy.js.erb
$('#segment_<%= @segment.id %>').hide().remove();

app/views/segments/edit.js.erb
$('#segment_<%= @segment.id %>_header').hide().after('<%= j render("edit_form")  %>');

$('#segment_<%= @segment.id %>').find('.job-type-count').hide();

$('#cancel_rename_<%= @segment.id %>').click( function () {
    $('#segment_<%= @segment.id %>_header').show().next().remove();
    $('#segment_<%= @segment.id %>').find('.job-type-count').show();
    return false;
});

app/views/segments/index.js.erb
$('#job_product_line_id').removeClass("ajax-loading");
$('#job_product_line_id').find('option').remove();

$('<option>').val('-1').text('Select a Segment...').appendTo('#job_product_line_id');

<% @segment.product_lines.each do |s| %>
    $('<option>').val('<%= s.id %>').text('<%= s.name %>').appendTo('#job_product_line_id');
<% end %>

$('#job_templates_list').find('*').remove();
$('#job_templates_list').append("<i>Select a product line to view job types</i>");

<% if @segment.product_lines.count == 0 %>
    $('#job_product_line_id').attr("disabled", "disabled");
    $('#job_product_line_id').css("opacity", ".3");
<% else %>
    $('#job_product_line_id').removeAttr("disabled");
    $('#job_product_line_id').css("opacity", "1");
<% end %>

app/views/segments/new.js.erb
$('#new_segment_link_<%= @segment.division.id %>').hide().after('<%= j render("form")  %>');

$('#cancel_segment_<%= @segment.division.id %>').click( function () {

    $('#new_segment_id_<%= @segment.division.id %>').remove();
    $('#new_segment_link_<%= @segment.division.id %>').show();
    return false;
});

app/views/segments/show.html.erb
<% provide(:title, 'Segment: ' + @segment.name) %>

<div class="page_header">
  <h1><%= @segment.name %></h1>

  <h3 class="inline">&nbsp;Segment</h3>

  <h2 class="paginated-count">Jobs:
    <%= render 'layouts/paged_header', items: @jobs %>
  </h2>

</div>

<% if !@is_paged %>
    <div class="well">
      <%= render 'jobs/index_parts/jobs_count', jobs: UserRole.limit_jobs_scope(current_user, @segment.jobs) %>
    </div>
    <br>

    <% if !current_user.role.limit_to_assigned_jobs? %>
        <div class="">
          <%= render 'jobs/index_parts/product_lines', segment: @segment %>
        </div>
    <% end %>
<% end %>


<div id="jobs" class="list">
  <% @jobs.each do |job| %>
      <%= render 'jobs/job_progress_link', job: job %>
  <% end %>
</div>

<% if @is_paged %>
    <%= will_paginate @jobs %>
<% else %>
    <br>
    <div class="alert">
      <%= link_to "View all jobs active and closed (" + @segment.jobs.count.to_s + ")", segment_path(:page => "1"), class: "activity-user-link" %>
    </div>
    <% if @jobs.empty? %>
        <div class="no-alerts">
          <p class="center"><%= t ".no_jobs" %></p>
        </div>
    <% end %>
<% end %>

app/views/segments/update.js.erb
$('#segment_<%= @segment.id %>').find('.product-line-header:first').text('<%= @segment.name %>');
$('#segment_<%= @segment.id %>_header').show();
$('#segment_<%= @segment.id %>_header').next().remove();

$('#segment_<%= @segment.id %>').find('.job-type-count').show();