config/routes.rb
ElephantWebApp::Application.routes.draw do


    root to: 'static_pages#home'

    match '/help', to: 'static_pages#help'
    match '/features', to: 'static_pages#features'
    match '/about', to: 'static_pages#about'
    match '/sales', to: 'static_pages#sales'
    match '/overview', to: 'overview#overview', :via => :get
    match '/insight', to: 'explore#index', :via => :get
    match '/overview', to: 'overview#filter_overview', :via => :post
    match '/terms_of_use', to: 'static_pages#terms_of_use'
    match '/tutorial', to: 'static_pages#tutorial'
    match '/terms', to: 'static_pages#terms'
    match '/privacy', to: 'static_pages#privacy'
    match '/copyright', to: 'static_pages#copyright'

    match '/pusher/auth', to: 'pusher#auth'

    resources :users, only: [:index, :show, :new, :create, :destroy, :edit, :update]

    resources :user_roles, only: [:index, :show, :new, :create, :destroy, :edit, :update]

    resources :sessions, only: [:create, :destroy]

    #match "/settings" => "settings#edit", :via => :get
    #match "/settings" => "settings#update", :via => :put
    resources :settings, only: [:edit, :update, :security, :update_security]
    match '/security', to: 'settings#security'
    match '/update_security', to: 'settings#update_security'

    match '/signin', to: 'sessions#new'
    match '/is_signed_in', to: 'sessions#show'
    get '/update_password', to: 'sessions#edit'
    match '/create_password', to: 'sessions#update', via: :post
    match '/signout', to: 'sessions#destroy', via: :delete
    match '/reset_password', to: 'sessions#reset_password'
    match '/verify_network', to: 'sessions#verify_network'

    resources :elephant_admin, only: [:index]
    match '/elephant_admin', to: 'elephant_admin#index'

    resources :companies, only: [:new, :destroy, :create, :show, :edit, :update]

    resources :job_templates, only: [:index, :new, :create, :destroy, :show, :edit, :update]

    resources :clients, only: [:index, :new, :create, :destroy, :show, :edit, :update]

    resources :districts, only: [:index, :new, :create, :destroy, :show, :edit, :update]

    resources :countries, only: [:show]

    resources :divisions, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :segments, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :product_lines, only: [:index, :show, :new, :create, :edit, :update, :destroy]

    resources :documents, only: [:show, :new, :create, :update, :destroy]

    resources :dynamic_fields, only: [:index, :show, :new, :create, :edit, :update, :destroy]

    resources :activities, only: [:index, :show]



    resources :jobs, only: [:index, :show, :new, :create, :update, :destroy]

    resources :fields, only: [:index, :show, :new, :create]

    resources :wells, only: [:index, :show, :new, :create, :edit, :update]
    resources :rigs, only: [:index, :new, :create, :show]



    resources :search, only: [:new, :create, :index]

    resources :history, only: [:index]
    resources :insight, only: [:index]

    resources :alerts, only: [:index]


    resources :job_notes, only: [:new, :create, :destroy]

    resources :job_memberships, only: [:new, :edit, :update, :create, :destroy]

    resources :job_note_comments, only: [:create, :destroy]

    resources :conversations, only: [:index, :show, :new, :create, :destroy, :update]

    resources :tools, only: [:new, :create, :edit, :update, :destroy]
    resources :primary_tools, only: [:index, :create, :destroy, :show, :update]
    resources :secondary_tools, only: [:index, :new, :create, :update, :destroy]

    resources :failures, only: [:index, :new, :show, :create, :edit, :update, :destroy]

    resources :post_job_report_documents, only: [:create, :update, :destroy]

    resources :document_shares, only: [:index, :show, :new, :create, :update, :destroy]


    # Inventory
    resources :inventory, only: [:index, :show]
    resources :parts, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy]
    resources :suppliers, only: [:show, :new, :create, :edit, :update, :destroy]
    resources :warehouse_memberships, only: [:new, :edit, :update, :create, :destroy]

    resources :part_memberships, only: [:new, :create, :edit, :update, :destroy]


    resources :job_logs, only: [:index, :create, :show]
    resources :drilling_logs, only: [:index, :show]
    resources :drilling_log_entries, only: [:show, :new, :create, :show, :edit, :update, :destroy]

    resources :job_times, only: [:index, :update]


    resources :bhas, only: [:show, :new, :create, :edit, :update, :destroy]

    resources :issues, only: [:index, :show, :create, :edit, :update, :destroy]

    resources :surveys, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources :survey_points, only: [:new, :create, :edit, :update, :destroy]

    resources :rig_memberships, only: [:new, :create, :destroy]

    resources :shipments, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :shippers, only: [:index, :show, :new, :create, :edit, :update, :destroy]

    resources :asset_lists, only: [:index, :show]
    resources :asset_list_entries, only: [:show, :new, :create, :edit, :update, :destroy]

    resources :job_costs, only: [:index, :show, :new, :create, :edit, :update, :destroy]

    match '/report_status/:id', to: 'reports#status', :via => :get

    resources :survey_projections, only: [:new, :create]

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
    before_filter :signed_in_user, only: [:show, :new, :create, :update, :destroy]

    respond_to :js

    include JobLogHelper

    def show

        @document = Document.find(params[:id])
        not_found unless !@document.nil?

        respond_to do |format|
            format.html {
                not_found
            }
            format.xlsx {
                excel = nil
                case @document.document_type
                    when Document::JOB_LOG
                        excel = logs_to_excel(JobLog.where(:company_id => current_user.company_id).where(:document_id => @document.id).order("entry_at ASC"), @document)
                end
                if excel.present?
                    send_data excel.to_stream.read, :filename => "#{@document.name}.xlsx", :type => "application/vnd.openxmlformates-officedocument.spreadsheetml.sheet"
                end
            }
            format.js {
                if params[:reorder].present?
                    if params[:reorder] == "-1"
                        puts @document.ordering.to_s + "....................."
                        if @document.ordering > 0
                            Document.transaction do
                                @document.ordering -= 1
                                @document.save

                                @document.document_collection.each do |document|
                                    if document != @document and (document.ordering || 0) == @document.ordering
                                        document.ordering = (document.ordering || 0) + 1
                                        document.save
                                    end
                                end
                            end

                            @move_up = true

                            render 'documents/reorder'
                        else
                            render :nothing => true, :status => :ok
                        end
                    end
                end
            }
            format.xml {
                render xml: @document,
                       :methods => [:full_url, :upload_info],
                       include: {
                               :document_template => {
                                       :methods => :full_url,
                               },
                               :user => {except: [:created_at, :updated_at, :password_digest, :remember_token, :elephant_admin, :create_password]}
                       }
            }
        end
    end

    def new

        if params["modal"].present? && params["modal"] == "true"
            @job_id = params[:job_id]
            @part_redress_id = params[:part_redress]
            @issue_id = params[:issue]
            @document = Document.new
            render 'documents/new_modal'
        elsif params["multi"].present? && params["multi"] == "true"
            @document = Document.new
            @document.name = File.basename(params[:name], ".*" )
            if params[:name].length > 149
                @document.name = @document.name[0..149]
            end
            @document.company = current_user.company
            @document.job = Job.find_by_id(params[:job_id])
            @temp_id = params[:temp_id]
            @document.save
            render 'documents/create_multi'
        else
            @document = Document.new(params[:document])
            @filename ||= File.basename(@document.url)

            render 'documents/new'
        end

    end

    def create

        job_id = params[:document][:job_id]
        params[:document].delete(:job_id)

        job_template_id = params[:document][:job_template_id]
        params[:document].delete(:job_template_id)

        primary_tool_id = params[:document][:primary_tool_id]
        params[:document].delete(:primary_tool_id)

        owner_id = params[:document][:owner_id]
        params[:document].delete(:owner_id)

        owner_type = params[:document][:owner_type]
        params[:document].delete(:owner_type)

        @document = Document.new(params[:document])
        if @document.template?
            @document.access_level = 0
            if @document.document_type == Document::PROTECTED_DOCUMENT
                @document.document_type = Document::DOCUMENT
                @document.access_level = Document::DOCUMENT_RESTRICTED
            end
        end
        @document.company = current_user.company

        if @document.template?

            @document.job_template = JobTemplate.find_by_id(job_template_id)
            @document.ordering = @document.document_collection.count

            if !primary_tool_id.blank?
                @document.primary_tool = PrimaryTool.find_by_id primary_tool_id
            end

            if !@document.save
                render 'error'
            end

            if @document.category == Document::NOTICES
                @document.delay.add_notices_on_active_jobs
            end

            Activity.delay.add(self.current_user, Activity::DOCUMENT_CREATED, @document, @document.name)
        else

            if job_id.present?
                @job = Job.find_by_id(job_id)
                not_found unless @job.company == current_user.company
                @document.job = @job
                @document.ordering = @document.document_collection.count
            elsif owner_id.present?
                owner = owner_type.constantize.find(owner_id)
                not_found unless owner.company == current_user.company
                @document.owner = owner
            end

            if @document.save
                render 'documents/create_modal'
            else
                render 'error'
            end

        end

    end

    def update
        @document = Document.find(params[:id])

        if @document.template?
            not_found unless signed_in_admin?
        end

        if !@document.template? && !@document.url.blank?
            document_revision = DocumentRevision.new
            document_revision.document = @document
            document_revision.company = @document.company
            document_revision.user = @document.user
            document_revision.user_name = @document.user_name
            document_revision.upload_date = @document.updated_at
            document_revision.url = @document.url
            document_revision.save
        end

        @document.user = current_user
        @document.user_name = current_user.name
        @document.url = params[:document][:url]

        if @document.template?
            @document.access_level = 0
            if params[:document][:document_type] == Document::PROTECTED_DOCUMENT
                @document.document_type = Document::DOCUMENT
                @document.access_level = Document::DOCUMENT_RESTRICTED
            end
        end

        @document.save

        if !@document.template?
            Activity.delay.add(current_user, Activity::DOCUMENT_UPLOADED, @document, @document.file_name, @document.job)
        end

        respond_to do |format|
            format.js {
                render 'documents/update'
            }
            format.xml { render xml: @document,
                                :methods => :full_url,
                                include: {
                                        :document_template => {
                                                :methods => :full_url,
                                        },
                                        :user => {except: [:created_at, :updated_at, :password_digest, :remember_token, :elephant_admin, :create_password]}
                                }
            }
        end
    end


    def destroy
        @document = Document.find(params[:id])
        not_found unless @document.company == current_user.company
        @document.delete_document
        @document.destroy

        if !@document.destroy
            render 'error'
        end

        #if @document.category == Document::NOTICES
        #    @document.delay.delete_notice_on_jobs @document.id
        #end

        @document.document_collection.each do |document|
            if document != @document and (document.ordering || 0) > @document.ordering
                document.ordering = (document.ordering || 0) - 1
                document.save
            end
        end

        Activity.delay.add(self.current_user, Activity::DOCUMENT_DESTROYED, @document, @document.name)

    end

end

app/views/documents/_document_metadata.html.erb
<div class="upload-metadata inline-block align-top">

<% if !document.template? %>
    <% last_entry = document.document_type == Document::JOB_LOG ? JobLog.where(:company_id => current_user.company_id).where(:document_id => document.id).last : nil %>
    <% drilling_log_sql = DrillingLog.where(:company_id => current_user.company_id).where(:document_id => document.id).select(:id).to_sql %>
    <% last_drilling_entry = document.document_type == Document::DRILLING_LOG ? DrillingLogEntry.where("drilling_log_entries.drilling_log_id IN (#{drilling_log_sql})").order("drilling_log_entries.created_at DESC").limit(1).first : nil %>
    <% bha = document.document_type == Document::BOTTOM_HOLE_ASSEMBLY ? Bha.includes(document: {job: :well}).where("wells.id = ?", document.job.well_id).order("bhas.updated_at DESC").limit(1).first : nil %>
    <% asset_list = document.document_type == Document::ASSET_LIST ? AssetList.where("asset_lists.job_id = ?", document.job_id).limit(1).first : nil %>
    <% if  document.document_type == Document::SURVEY %>
        <% survey = Survey.includes(document: {job: :well}).where(:company_id => current_user.company_id).where(:plan => false).where("wells.id = ?", document.job.well_id).limit(1).first %>
    <% elsif document.document_type == Document::WELL_PLAN %>
        <% survey = Survey.includes(document: {job: :well}).where(:company_id => current_user.company_id).where(:plan => true).where("wells.id = ?", document.job.well_id).limit(1).first %>
    <% end %>
<% end %>

<% if false %>
<% if !document.template? && document.job_id.present? %>
    <div class="document-status">
      <% if !document.empty? %>
          <%= image_tag "document_complete.png", class: "tooltip-info",
                        "data-placement" => "bottom",
                        "data-title" => "Complete" %>
      <% elsif document.category == Document::NOTICES %>
          <%= image_tag "warning.png" %>
      <% end %>
    </div>
<% end %>
    <% end %>

<% if !document.template? %>
    <% if document.document_type == Document::DOCUMENT %>
        <% if document.url.present? %>
            <%= link_to document.name, document.full_url, class: "document-name tooltip-info download-link",
                        "data-placement" => "bottom",
                        "data-title" => "Click to download document" %>

        <% elsif !document.document_template.nil? && document.document_template.url.present? %>
            <%= link_to document.name, document.document_template.full_url, class: "document-name tooltip-info download-link " + (!document.template? && document.category == Document::NOTICES ? "long-column-text" : ""),
                        "data-placement" => "bottom",
                        "data-title" => "Click to download document" %>
        <% else %>
            <p class="document-name push-down"><%= document.name %></p>
        <% end %>
    <% elsif document.document_type == Document::JOB_LOG %>
        <%= link_to document.name, job_logs_path(document: document.id),
                    class: "document-name tooltip-info",
                    "data-placement" => "bottom",
                    "data-title" => "Open " + document.document_type_string %>
    <% elsif document.document_type == Document::ASSET_LIST %>
        <%= link_to document.name, asset_lists_path(document: document.id),
                    class: "document-name tooltip-info",
                    "data-placement" => "bottom",
                    "data-title" => "Open " + document.document_type_string %>
    <% elsif document.document_type == Document::DRILLING_LOG %>
        <%= link_to document.name, drilling_logs_path(document: document.id, :anchor => "log"),
                    class: "document-name tooltip-info",
                    "data-placement" => "bottom",
                    "data-title" => "Open " + document.document_type_string %>
    <% elsif document.document_type == Document::BOTTOM_HOLE_ASSEMBLY %>
        <% drilling_log_document = Document.where("documents.job_id = ?", document.job_id).where("documents.document_type = ?", Document::DRILLING_LOG).first %>
        <% if !drilling_log_document.nil? %>
            <%= link_to document.name, drilling_logs_path(document: drilling_log_document.id, :anchor => "drilling-bha"),
                        class: "document-name tooltip-info",
                        "data-placement" => "bottom",
                        "data-title" => "Open " + document.document_type_string %>
        <% else %>
            <%= link_to document.name, bha_path(document),
                        class: "document-name tooltip-info",
                        "data-placement" => "bottom",
                        "data-title" => "Open " + document.document_type_string %>
        <% end %>
    <% elsif document.document_type == Document::WELL_PLAN %>
        <%= link_to document.name, surveys_path(document: document),
                    class: "document-name tooltip-info",
                    "data-placement" => "bottom",
                    "data-title" => "Open " + document.document_type_string %>
    <% elsif document.document_type == Document::SURVEY %>
        <% drilling_log_document = Document.where("documents.job_id = ?", document.job_id).where("documents.document_type = ?", Document::DRILLING_LOG).first %>
        <% if !drilling_log_document.nil? %>
            <%= link_to document.name, drilling_logs_path(document: drilling_log_document.id, :anchor => "survey"),
                        class: "document-name tooltip-info",
                        "data-placement" => "bottom",
                        "data-title" => "Open " + document.document_type_string %>
        <% else %>
            <%= link_to document.name, surveys_path(document: document),
                        class: "document-name tooltip-info",
                        "data-placement" => "bottom",
                        "data-title" => "Open " + document.document_type_string %>
        <% end %>
    <% end %>
<% else %>
    <% if document.url.present? %>
        <%= link_to document.name, document.full_url, class: "document-name tooltip-info",
                    "data-placement" => "bottom",
                    "data-title" => "Download document" %>
    <% else %>
        <p class="document-name align-top push-down"><%= document.name %></p>
    <% end %>
<% end %>

<div class="document-info <%= (!document.template? && document.category == Document::NOTICES ? "hidden" : "") %>">
  <% if !document.template? and !document.read_only? %>
      <div class="document-modified2">
        <% if document.document_type == Document::DOCUMENT %>
            <% if document.updated_at != document.created_at %>
                <p class="inline tooltip-info" data-placement="bottom" data-title="Last updated"><%= document.updated_at.strftime("%m/%d/%Y %l:%M %p") %></p>
            <% else %>
                <p class="warning-text tooltip-info push-down"
                   data-placement="bottom"
                   data-title="No document uploaded, please download the document by clicking the document name and upload the completed one">No
                  Document Uploaded</p>
            <% end %>
        <% elsif document.document_type == Document::JOB_LOG %>
            <% if last_entry.present? %>
                <p class="">
                  <%= last_entry.entry_at.strftime("%m/%d/%Y %l:%M %p") %>
                </p>
            <% else %>
                <p class="warning-text tooltip-info push-down"
                   data-placement="bottom"
                   data-title="No entries have been added to <%= document.document_type_string %>">
                  No Entries Added</p>
            <% end %>
        <% elsif document.document_type == Document::ASSET_LIST %>
            <% if asset_list.present? && asset_list.asset_list_enrties.any? %>
                <p class="">
                  <%= asset_list.asset_list_enrties.last.created_at.strftime("%m/%d/%Y %l:%M %p") %>
                </p>
            <% else %>
                <p class="warning-text tooltip-info push-down"
                   data-placement="bottom"
                   data-title="No entries have been added to <%= document.document_type_string %>">
                  No Entries Added</p>
            <% end %>
        <% elsif document.document_type == Document::DRILLING_LOG %>
            <% if last_drilling_entry.present? %>
                <p class="inline">
                  <%= last_drilling_entry.entry_at.strftime("%m/%d/%Y %l:%M %p") %>
                </p>
            <% else %>
                <p class="warning-text tooltip-info push-down"
                   data-placement="bottom"
                   data-title="No entries have been added to <%= document.document_type_string %>">
                  No Entries Added</p>
            <% end %>
        <% elsif document.document_type == Document::BOTTOM_HOLE_ASSEMBLY %>
            <% if bha.present? %>
                <p class="push-down">
                  <%= bha.updated_at.strftime("%m/%d/%Y %l:%M %p") %>
                </p>
            <% else %>
                <p class="warning-text tooltip-info push-down"
                   data-placement="bottom"
                   data-title="No assemblies have been added to <%= document.document_type_string %>">
                  No Assemblies Added</p>
            <% end %>
        <% elsif document.document_type == Document::SURVEY %>
            <% if survey.present? && survey.survey_points.any? %>
                <p class="push-down">
                  <%= survey.survey_points.last.updated_at.strftime("%m/%d/%Y %l:%M %p") %>
                </p>
            <% else %>
                <p class="warning-text tooltip-info push-down"
                   data-placement="bottom"
                   data-title="No survey points have been added to <%= document.document_type_string %>">
                  No Survey Points</p>
            <% end %>
        <% elsif document.document_type == Document::WELL_PLAN %>
            <% if survey.present? && survey.survey_points.any? %>
                <p class="push-down">
                  <%= survey.survey_points.order("created_at DESC").first.updated_at.strftime("%m/%d/%Y %l:%M %p") %>
                </p>
            <% else %>
                <p class="warning-text tooltip-info push-down"
                   data-placement="bottom"
                   data-title="No plan imported for <%= document.document_type_string %>">
                  No Plan Added</p>
            <% end %>
        <% end %>
      </div>

      <div class="document-file-name-box">
        <%= render 'documents/user', document: document, last_entry: last_entry, bha: bha, survey: survey, last_drilling_entry: last_drilling_entry %>

        <% if document.access_level > 1 %>
            <%= image_tag "lock_icon.png", class: "document-restricted tooltip-info",
                          "data-placement" => "bottom",
                          "data-title" => "Restricted Access" %>
        <% end %>
      </div>
  <% else %>
      <div class="document-modified">
        <% if document.url.present? %>
            <p class="inline tooltip-info" data-placement="bottom" data-title="Last updated"><%= document.updated_at.strftime("%m/%d/%Y %l:%M %p") %></p>
        <% end %>
      </div>


      <div class="document-file-name-box">
        <% if document.document_type == Document::DOCUMENT %>
            <% if document.template? or !document.read_only? %>
                <% if !document.url.nil? %>
                    <p class="document-file-name"><%= '"' + document.file_name + '"' %></p>
                <% else %>
                    <p class="warning-text tooltip-info align-top push-down"
                       data-placement="bottom"
                       data-title="No document uploaded, please upload a template">
                      No Document Uploaded</p>
                <% end %>
            <% end %>
        <% else %>
            <p class="tooltip-info align-top push-down"
               data-placement="bottom"
               data-title="Job Log document type"><b><%= document.document_type_string %></b></p>
        <% end %>
      </div>

      <% if document.access_level > 1 %>
          <%= image_tag "lock_icon.png", class: "document-restricted tooltip-info",
                        "data-placement" => "bottom",
                        "data-title" => "Restricted Access" %>
      <% end %>
  <% end %>


</div>

</div>

app/views/documents/_modal_new_document.html.erb
<div>
  <div class="section-header">
    <h1>Add New Document</h1>
  </div>

  <div class="form" data-form="new_document">
    <%= form_for document, remote: true do |f| %>

        <%= f.hidden_field :document_type, value: "0" %>
        <%= f.hidden_field :template, value: "false" %>
        <% if job_id.present? %>
            <%= f.hidden_field :job_id, value: job_id %>
        <% end %>
        <% if part_redress_id.present? %>
            <%= f.hidden_field :owner_id, value: part_redress_id %>
            <%= f.hidden_field :owner_type, value: "PartRedress" %>
            <%= f.hidden_field :category, value: Document::PART_REDRESS %>
        <% end %>
        <% if issue_id.present? %>
            <%= f.hidden_field :owner_id, value: issue_id %>
            <%= f.hidden_field :owner_type, value: "Issue" %>
            <%= f.hidden_field :category, value: Document::ISSUES %>
        <% end %>

        <div class="well">
          <b>New Document Name</b><br><br>
          <%= f.text_field :name, class: "txtfield",
                           placeholder: "Document Name..." %>
        </div>

        <% if job_id.present? %>
            <div class="content">
              <div class="">
                <div class="list-item-column2">Category</div>
                <%= f.select :category, options_for_select([["Pre-Job", Document::PRE_JOB], ["On-Job", Document::ON_JOB], ["Post-Job", Document::POST_JOB]]),
                             {},
                             class: "job-note-type custom-select" %>
              </div>


              <% if !current_user.role.limit_to_assigned_jobs? %>
                  <br>

                  <div>
                    <div class="list-item-column2">Access
                      Level
                      <%= image_tag "lock_icon.png", class: "tooltip-info align-top push-right-small push-down-small",
                                    "data-placement" => "bottom",
                                    "data-title" => "Restricted Access" %>
                    </div>
                    <%= f.select :access_level, options_for_select([["Available to All", 0], ["Restricted to Corporate", 3]]),
                                 {},
                                 class: "job-note-type custom-select inline" %>
                  </div>

              <% end %>
            </div>

            <br>
        <% end %>


        <div class="custom-document-footer">
          <%= f.submit class: "btn btn-success pull-right form-loading-on-click",
                       "data-form" => "new_document" %>
        </div>


    <% end %>

  </div>


  <div class="form-loading hidden" data-form="new_document">
    <%= render 'layouts/inline_loading', title: "Creating..." %>
  </div>
</div>

app/views/documents/_user.html.erb
<% user = nil %>
<% if document.document_type == Document::DOCUMENT %>
    <% if document.url.present? %>
        <% if document.user.present? %>
            <% user = document.user %>
        <% end %>
    <% end %>
<% else %>
    <% if last_entry.present? %>
        <% user = last_entry.user %>
    <% elsif last_drilling_entry.present? %>
        <% user = last_drilling_entry.user %>
    <% elsif survey.present? && survey.survey_points.any? %>
        <% user = survey.survey_points.last.user %>
    <% elsif bha.present? %>
    <% end %>
<% end %>

<% if user.present? %>
    <% if document.job.present? %>
        <% job_membership = document.job.job_memberships.where(:user_id => user.id).last %>
    <% end %>
    <% if job_membership.present? %>
        <%= render 'job_memberships/icon', job_membership: job_membership %>
    <% else %>
        <%= render 'users/icon', user: document.user %>
    <% end %>
<% elsif !document.user_name.blank? %>
    <div class="member-icon tooltip-info" data-title="<%= document.user_name %>">
      <% names = document.user_name.split(" ") %>
      <p>
        <% if names.any? %>
            <%= names.count > 1 ? names.first[0, 1] + names.last[0, 1] : names.first[0, 1] %>
        <% else %>
            -
        <% end %>
      </p>
    </div>
<% end %>

app/views/documents/create_multi.js.erb
$("#documents").append("<%= j render @document, in_job: true %>");
var doc = $('.root-document:last')
doc.attr("data-temp-id", "<%= @temp_id %>");

app/views/documents/destroy.js.erb
$('#document_<%= @document.id %>').hide().remove();

app/views/documents/error.js.erb
$('#modal_popup').find('.loading').addClass('hidden');
$('#modal_popup').find('.form').show();

$('#alert').remove();
$('body').append("<%= j render 'layouts/modal_error', title: "Problem Adding Document", message: @document.errors.full_messages.join(', ').html_safe %>");
$('#alert').modal({show:true});

app/views/documents/new.js.erb
$('#documents').append('<%= j render(@document)  %>')

app/views/documents/reorder.js.erb
<% if @move_up %>

var doc = $('#document_<%= @document.id.to_s %>');
var prev = doc.prev();
doc.remove();
prev.before(doc);

doc.addClass('document-reorder-background');
setTimeout(function() { doc.removeClass('document-reorder-background') }, 1000);

<% end %>