config/routes.rb
ElephantWebApp::Application.routes.draw do


    root to: 'static_pages#home'

    match '/help', to: 'static_pages#help'
    match '/features', to: 'static_pages#features'
    match '/about', to: 'static_pages#about'
    match '/sales', to: 'static_pages#sales'
    match '/overview', to: 'overview#overview', :via => :get
    match '/insight', to: 'explore#index', :via => :get
    match '/overview', to: 'overview#filter_overview', :via => :post
    match '/terms_of_use', to: 'static_pages#terms_of_use'
    match '/tutorial', to: 'static_pages#tutorial'
    match '/terms', to: 'static_pages#terms'
    match '/privacy', to: 'static_pages#privacy'
    match '/copyright', to: 'static_pages#copyright'

    match '/pusher/auth', to: 'pusher#auth'

    resources :users, only: [:index, :show, :new, :create, :destroy, :edit, :update]

    resources :user_roles, only: [:index, :show, :new, :create, :destroy, :edit, :update]

    resources :sessions, only: [:create, :destroy]

    #match "/settings" => "settings#edit", :via => :get
    #match "/settings" => "settings#update", :via => :put
    resources :settings, only: [:edit, :update, :security, :update_security]
    match '/security', to: 'settings#security'
    match '/update_security', to: 'settings#update_security'

    match '/signin', to: 'sessions#new'
    match '/is_signed_in', to: 'sessions#show'
    get '/update_password', to: 'sessions#edit'
    match '/create_password', to: 'sessions#update', via: :post
    match '/signout', to: 'sessions#destroy', via: :delete
    match '/reset_password', to: 'sessions#reset_password'
    match '/verify_network', to: 'sessions#verify_network'

    resources :elephant_admin, only: [:index]
    match '/elephant_admin', to: 'elephant_admin#index'

    resources :companies, only: [:new, :destroy, :create, :show, :edit, :update]

    resources :job_templates, only: [:index, :new, :create, :destroy, :show, :edit, :update]

    resources :clients, only: [:index, :new, :create, :destroy, :show, :edit, :update]

    resources :districts, only: [:index, :new, :create, :destroy, :show, :edit, :update]

    resources :countries, only: [:show]

    resources :divisions, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :segments, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :product_lines, only: [:index, :show, :new, :create, :edit, :update, :destroy]

    resources :documents, only: [:show, :new, :create, :update, :destroy]

    resources :dynamic_fields, only: [:index, :show, :new, :create, :edit, :update, :destroy]

    resources :activities, only: [:index, :show]



    resources :jobs, only: [:index, :show, :new, :create, :update, :destroy]

    resources :fields, only: [:index, :show, :new, :create]

    resources :wells, only: [:index, :show, :new, :create, :edit, :update]
    resources :rigs, only: [:index, :new, :create, :show]



    resources :search, only: [:new, :create, :index]

    resources :history, only: [:index]
    resources :insight, only: [:index]

    resources :alerts, only: [:index]


    resources :job_notes, only: [:new, :create, :destroy]

    resources :job_memberships, only: [:new, :edit, :update, :create, :destroy]

    resources :job_note_comments, only: [:create, :destroy]

    resources :conversations, only: [:index, :show, :new, :create, :destroy, :update]

    resources :tools, only: [:new, :create, :edit, :update, :destroy]
    resources :primary_tools, only: [:index, :create, :destroy, :show, :update]
    resources :secondary_tools, only: [:index, :new, :create, :update, :destroy]

    resources :failures, only: [:index, :new, :show, :create, :edit, :update, :destroy]

    resources :post_job_report_documents, only: [:create, :update, :destroy]

    resources :document_shares, only: [:index, :show, :new, :create, :update, :destroy]


    # Inventory
    resources :inventory, only: [:index, :show]
    resources :parts, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy]
    resources :suppliers, only: [:show, :new, :create, :edit, :update, :destroy]
    resources :warehouse_memberships, only: [:new, :edit, :update, :create, :destroy]

    resources :part_memberships, only: [:new, :create, :edit, :update, :destroy]


    resources :job_logs, only: [:index, :create, :show]
    resources :drilling_logs, only: [:index, :show]
    resources :drilling_log_entries, only: [:show, :new, :create, :show, :edit, :update, :destroy]

    resources :job_times, only: [:index, :update]


    resources :bhas, only: [:show, :new, :create, :edit, :update, :destroy]

    resources :issues, only: [:index, :show, :create, :edit, :update, :destroy]

    resources :surveys, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources :survey_points, only: [:new, :create, :edit, :update, :destroy]

    resources :rig_memberships, only: [:new, :create, :destroy]

    resources :shipments, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :shippers, only: [:index, :show, :new, :create, :edit, :update, :destroy]

    resources :asset_lists, only: [:index, :show]
    resources :asset_list_entries, only: [:show, :new, :create, :edit, :update, :destroy]

    resources :job_costs, only: [:index, :show, :new, :create, :edit, :update, :destroy]

    match '/report_status/:id', to: 'reports#status', :via => :get

    resources :survey_projections, only: [:new, :create]

end

app/models/job_template.rb
class JobTemplate < ActiveRecord::Base
    attr_accessible :name,
                    :dynamic_fields_attributes,
                    :documents_attributes,
                    :description,
                    :track_accessories

    acts_as_tenant(:company)


    validates :name, presence: true, length: {maximum: 100}
    validates_uniqueness_of :name, :case_sensitive => false, :scope => :product_line_id
    validates :company, presence: true
    validates :product_line, presence: true

    belongs_to :company
    belongs_to :product_line

    has_many :dynamic_fields, order: "ordering ASC", :conditions => ['dynamic_fields.template = ?', true]
    accepts_nested_attributes_for :dynamic_fields, :allow_destroy => true

    has_many :documents, order: "ordering ASC", :conditions => ['documents.template = ?', true]
    accepts_nested_attributes_for :documents, :allow_destroy => true

    has_many :primary_tools, :conditions => {:template => true }
    has_many :post_job_report_documents, order: "ordering ASC", :dependent => :destroy
    has_many :failures, dependent: :destroy, order: "text ASC"

    searchable do
        text :name, :as => :code_textp
        integer :company_id
    end

    def self.from_company(company)
        where("company_id = :company_id", company_id: company.id)
    end

    def jobs
        self.company.jobs.joins(:job_template).where("job_templates.id = ?", self.id)
    end

    def active_jobs
        Job.where("jobs.company_id = ?", self.company_id).where("jobs.status >= 1 AND jobs.status < 50").joins(:job_template).where("job_templates.id = ?", self.id)
    end

    def self.from_company_for_user(job_template, options, user, company)
        Sunspot.search(Job) do
            with(:job_template_id, job_template.id)
            any_of do
                if user.role.limit_to_assigned_jobs?
                    with(:job_membership, user.id)
                elsif user.role.limit_to_district?
                    with(:district_id, user.district.id)
                elsif user.role.limit_to_product_line? && !user.product_line.nil?
                    with(:product_line_id, user.product_line.id)
                end
            end
            with(:company_id, company.id)
            order_by :created_at, :desc
            paginate :page => options[:page]
        end
    end

    def self.search(options, company)
        Sunspot.search(JobTemplate) do
            fulltext options[:search].present? ? options[:search] : options[:term]
            with(:company_id, company.id)
            #order_by :name, :asc
            paginate :page => options[:page]
        end
    end

    def notices_documents
        self.documents.where(:category => Document::NOTICES)
    end

    def pre_job_documents
        self.documents.where(:category => Document::PRE_JOB)
    end

    def on_job_documents
        self.documents.where(:category => Document::ON_JOB)
    end

    def post_job_documents
        self.documents.where(:category => Document::POST_JOB)
    end

    def post_job_report_document_options
        collection = []

        collection << ["", -1]
        collection << ["(+) New Document exclusively for report", 0]
        collection << ["(+) Job Custom Data", -10]
        collection << ["", -1]

        collection << [Document::NOTICES + " (" + notices_documents.count.to_s + ") ------------------------", -1]
        notices_documents.each do |document|
            collection << [document.name, document.id]
        end

        collection << ["", -1]
        collection << [Document::PRE_JOB + " (" + pre_job_documents.count.to_s + ") ------------------------", -1]
        pre_job_documents.each do |document|
            collection << [document.name, document.id]
        end

        collection << ["", -1]
        collection << [Document::ON_JOB + " (" + on_job_documents.count.to_s + ") ------------------------", -1]
        on_job_documents.each do |document|
            collection << [document.name, document.id]
        end

        collection << ["", -1]
        collection << [Document::POST_JOB + " (" + post_job_documents.count.to_s + ") ------------------------", -1]
        post_job_documents.each do |document|
            collection << [document.name, document.id]
        end

        collection
    end

end

app/controllers/job_templates_controller.rb
class JobTemplatesController < ApplicationController
    before_filter :signed_in_admin, only: [:index, :new, :create, :edit, :update, :destroy]
    before_filter :signed_in_user, only: [:show]
    set_tab :job_templates

    def index
        respond_to do |format|
            format.html {
                @product_lines = ProductLine.from_company(current_user.company).order("name ASC")

                @count = 0
                @product_lines.each do |product_line|
                    @count += product_line.job_templates.count
                end
            }
            format.json {
                @job_templates = JobTemplate.search(params, current_user.company).results
                render json: @job_templates.map { |job_template| {:label => job_template.name, :product_line => job_template.product_line.name, :segment => job_template.product_line.segment.name, :division => job_template.product_line.segment.division.name, :id => job_template.id} }
            }
        end
    end


    def show

        @job_template = JobTemplate.find(params[:id])
        not_found unless @job_template.company == current_user.company

        if signed_in_admin?
            @new_document = Document.new
            @new_dynamic_field = DynamicField.new
        else
            respond_to do |format|
                format.js {
                    render 'job_templates/show'
                }
                format.html {

                    @is_paged = params[:page].present?
                    if @is_paged
                        @jobs = @job_template.jobs.includes(dynamic_fields: :dynamic_field_template).includes(:field, :well, :documents, :district, :client, :job_template => {:primary_tools => :tool}).includes(job_template: {product_line: {segment: :division}}).reorder('').order("jobs.created_at DESC").paginate(page: params[:page], limit: 20)
                    else
                        @jobs = @job_template.jobs.includes(dynamic_fields: :dynamic_field_template).includes(:field, :well, :documents, :district, :client, :job_template => {:primary_tools => :tool}).includes(job_template: {product_line: {segment: :division}}).reorder('').where("(jobs.status >= 1 AND jobs.status < 50) OR (jobs.status = :status_closed AND jobs.close_date >= :close_date)", status_closed: Job::COMPLETE, close_date: (Time.now - 5.days)).
                                order("jobs.created_at DESC")
                    end

                    render 'job_templates/show_jobs'
                }
            end
        end
    end

    def new
        @job_template = JobTemplate.new
        @job_template.product_line = ProductLine.find_by_id(params[:product_line])
        @product_lines = ProductLine.from_company(current_user.company)

        @documents = Array.new

        @value_types = Array.new
        @value_types << "String"
        @value_types << "Number"
        @value_types << "Boolean"
    end

    def create

        product_line = ProductLine.find_by_id(params[:job_template][:product_line_id])
        params[:job_template].delete(:product_line_id)
        not_found unless product_line.company == current_user.company

        @job_template = JobTemplate.new(params[:job_template])

        @fields = params[:job_template][:dynamic_fields]

        @job_template.company = current_user.company
        @job_template.product_line = product_line

        if @job_template.save

            Activity.add(self.current_user, Activity::JOB_TEMPLATE_CREATED, @job_template, @job_template.name)

            flash[:success] = "Job Template created - #{@job_template.name}"
            redirect_to @job_template
        else
            @product_lines = ProductLine.from_company(current_user.company)
            render 'new'
        end
    end

    def edit
        @job_template = JobTemplate.find(params[:id])
        not_found unless @job_template.company == current_user.company


        @product_lines = ProductLine.from_company(current_user.company)

        @value_types = Array.new
        @value_types << "String"
        @value_types << "Number"
        @value_types << "Boolean"
    end

    def update
        if params[:track_accessories].present?
            @job_template = JobTemplate.find(params[:id])
            not_found unless @job_template.company == current_user.company

            @job_template.update_attribute(:track_accessories, params[:track_accessories] == "true")
            render :nothing => true, :status => 200
        else
            product_line_id = params[:job_template][:product_line_id]
            params[:job_template].delete(:product_line_id)

            @job_template = JobTemplate.find(params[:id])
            not_found unless @job_template.company == current_user.company

            @fields = params[:job_template][:dynamic_fields]
            @documents = params[:job_template][:document_fields]

            if product_line_id.present?
                @job_template.product_line = ProductLine.find(product_line_id)
            end

            if @job_template.update_attributes(params[:job_template])

                #Activity.add(self.current_user, Activity::JOB_TEMPLATE_UPDATED, @job_template, @job_template.name)

                flash[:success] = "Job Template updated"
                redirect_to job_templates_path
            else
                @product_lines = ProductLine.from_company(current_user.company)
                render 'edit'
            end
        end
    end

    def destroy
        @job_template = JobTemplate.find(params[:id])
        not_found unless @job_template.company == current_user.company

        if current_user.company.jobs.where("jobs.job_template_id = ?", @job_template.id).any?
            render 'job_templates/elephant_destroy'
            return
        else
            @job_template.destroy

            Activity.add(self.current_user, Activity::JOB_TEMPLATE_DESTROYED, @job_template, @job_template.name)

            flash[:success] = "Job Type deleted."
            redirect_to divisions_path
        end
    end

end

app/views/job_templates/_document_fields.html.erb
<%= form_for @new_document, remote: true do |f| %>

    <%= render 'shared/error_messages', object: f.object %>

    <div class="inline-form">

      <%= f.text_field :name, placeholder: I18n.t("job_templates.document_fields.name"),
                       class: "txtfield tooltip-info align-top",
                       id: "new_document_name",
                       "data-placement" => "bottom",
                       "data-title" => "Document name" %>

      <%= f.select :document_type, options_for_select([["Document", Document::DOCUMENT],
                                                       ["Protected Document", Document::PROTECTED_DOCUMENT],
                                                       ["Asset List", Document::ASSET_LIST],
                                                       ["Job Log", Document::JOB_LOG],
                                                       ["Bottom Hole Assembly", Document::BOTTOM_HOLE_ASSEMBLY],
                                                       ["Drilling Log", Document::DRILLING_LOG],
                                                       ["Well Plan", Document::WELL_PLAN],
                                                       ["Survey", Document::SURVEY]
                                                        ]),
                   {},
                   class: "job-note-type custom-select" %>

      <%= f.hidden_field :read_only, value: read_only %>
      <%= f.hidden_field :template, value: true %>
      <%= f.hidden_field :category, value: category_name %>
      <%= f.hidden_field :job_template_id, value: @job_template.id %>

      <%= f.submit "+ Add to " + category_name,
                   class: "bluebtn btnsmall tooltip-info add-new-document-button",
                   "data-placement" => "bottom",
                   "data-title" => "Add new document to " + category_name %>

    </div>

<% end %>

app/views/job_templates/_dynamic_field_fields.html.erb
<%= form_for @new_dynamic_field, remote: true do |f| %>

    <%= render 'shared/error_messages', object: f.object %>

    <div class="inline-form well">

      <h3 class="job-dynamic-field-title">New Custom Data Property</h3>

      <%= f.text_field :name, placeholder: "Custom data property name", class: "txtfield tooltip-info", id: "new_dynamic_field_name",
                       "data-placement" => "bottom",
                       "data-title" => "Custom data property name" %>
      <!-- <%= f.select :value_type, options_for_select(@new_dynamic_field.units) %>   -->
      <%= f.hidden_field :template, value: true %>
      <%= f.hidden_field :job_template_id, value: @job_template.id %>

      <%= f.select :value_type,
                   options_for_select(@new_dynamic_field.units),
                   {},
                   class: "tooltip-info", "data-placement" => "bottom",
                   "data-title" => "Units of field, click to change" %>

      <%= f.submit I18n.t("global.add"), class: "bluebtn btnsmall" %>

      <br>

      <div class="dynamic-field-options">
        <div class="inline tooltip-info" data-placement="bottom"
             data-title="This data is pre-defined and non-editable on the job page">
          <%= f.label "Preset Value?", class: "checkbox-label" %>

          <%= f.text_field :value,
                           placeholder: "-",
                           class: "job-field-value-editable push-right-small" %>
        </div>

        <div class="inline tooltip-info push-right" data-placement="bottom"
             data-title="This data is shown in the summary of the job">
          <%= f.check_box :priority,
                          class: "regular-checkbox", id: "checkbox_1" %>
          <label for="checkbox_1"></label>
          <%= f.label "Show in job summary", class: "checkbox-label" %>
        </div>

        <div class="inline tooltip-info push-right" data-placement="bottom"
             data-title="This data is a tool used on the job">
          <%= f.check_box :optional,
                          class: "regular-checkbox", id: "checkbox_2" %>
          <label for="checkbox_2"></label>
          <%= f.label "Optional", class: "checkbox-label" %>
        </div>
      </div>


    </div>
<% end %>

app/views/job_templates/_fields.html.erb
<div class="">

  <%= f.hidden_field :product_line_id, value: @job_template.product_line.id %>

  <div class="well">
    <div class="">
      <h3 class="">Job Type Name</h3><br>
      <%= f.text_field :name, value: @job_template.name, class: "txtfield", placeholder: I18n.t("job_templates.show.job_type_name") %>
    </div>

    <div>
      <%= image_tag "division_extrasmall.png", class: "job-status-avatar" %>
      <b class="inline"><%= @job_template.product_line.segment.division.name %></b>
      |
      <b class="inline"><%= @job_template.product_line.segment.name %></b>
      |
      <b class="inline"><%= @job_template.product_line.name %></b>
    </div>

    <hr>


    <div class="">
      <%= f.text_area :description,
                      placeholder: I18n.t("job_templates.show.description_prompt"),
                      class: "txtfield job-description-text push-right-small", autofocus: false %>
    </div>
  </div>

</div>

app/views/job_templates/_job_template.html.erb
<div class="field">
  <%= link_to job_template, class: "list-item-header user-header job-type-header tooltip-info",
              "data-placement" => "left",
              "data-title" => "Click to open/edit job system" do %>
      <p class="list-item-header-text">
        <%= job_template.name %>
      </p>
  <% end %>
</div>

app/views/job_templates/_tray_accessories.html.erb
<div class="tray hidden" data-tray="accessories">
  <div class="page_header">
    <h1>Accessories</h1>

    <div class="pull-right push-down">
      <%= check_box_tag "track_accessories", "track_accessories", @job_template.track_accessories,
                        "data-job-template" => @job_template.id.to_s,
                        class: "regular-checkbox", id: "track_accessories" %>
      <label for="track_accessories"></label>

      <p class="checkbox-label">Track Accessories with Serial Number</p>
    </div>
  </div>

  <div>
    <br>

    <div>


      <% division = @job_template.product_line.segment.division %>
      <%= render 'tools/secondary/division_list', division: division %>

      <div class="loading hidden">
        <br>
        <span class="ajax-loading search-loading push-right"><b>Loading, please wait</b></span>
      </div>

    </div>

  </div>


</div>

app/views/job_templates/_tray_failures.html.erb
<div class="tray hidden" data-tray="failures">
  <div class="page_header">
    <h1>Failures</h1>
  </div>

  <br>

  <div class="content">
    <div id="failures_list">
      <% @job_template.failures.each do |failure| %>
          <%= render 'failures/failure', failure: failure %>
      <% end %>
    </div>

    <% if @job_template.failures.count == 0 %>
        <p class="job-type-no-failures"><b>0 failures</b> - No failures added, please add from selection </p>
    <% end %>

    <br>

    <div class="well">
      <%= form_for(Failure.new, :html => {:class => "inline"}, remote: true) do |f| %>
          <%= f.hidden_field :job_template_id, value: @job_template.id %>
          <%= f.select :failure_master_template_id, options_for_select(@job_template.product_line.failures.collect { |p| [p.text, p.id] }),
                       {prompt: "Select a Failure..."},
                       class: "tooltip-info custom-select custom-select-long",
                       "data-placement" => "bottom",
                       "data-title" => "Select from an existing failure on this product line" %>

          <%= f.submit "+ Add to Job Type", class: "bluebtn btnsmall" %>
      <% end %>

      <div>
        <br><br>

        <p class="push-right-small">
          <b>No failures above or not the one you want?</b>
        </p>
        <br>

        <p class="push-right-small">Add it to the product line so you can add it to the job type...</p>
        <br><br>
        <%= link_to "+ Add New failure on product line",
                    new_failure_path(:product_line => @job_template.product_line.id),
                    remote: true,
                    class: "bluebtn btnsmall gray tooltip-info show-modal-button",
                    id: "add_new_failure",
                    "data-placement" => "bottom",
                    "data-title" => "Add failure to job type" %>
      </div>
    </div>

    <br><br>

    <div class="alert">
      <b>Failures</b>

      <p>All possible failures that can happen on this job type.</p>
    </div>

  </div>
</div>

app/views/job_templates/_tray_post_job_reports.html.erb
<div class="tray hidden" data-tray="report">
  <div class="page_header">
    <h1>Post Job Report</h1>
  </div>

  <div class="content">
    <div id="post_job_documents_list">
      <% @job_template.post_job_report_documents.each do |post_job_document| %>
          <%= render 'post_job_report_documents/document',
                     post_job_report_document: post_job_document,
                     document: post_job_document.document,
                     editable: true,
                     can_upload: post_job_document.document.category == Document::POST_JOB_REPORT_PART && post_job_document.document.document_type == Document::DOCUMENT ? true : false %>
      <% end %>
    </div>

    <% if @job_template.post_job_report_documents.count == 0 %>
        <p class="job-type-no-docs-post-jobs-report"><b>0 documents</b> - No documents added for post job report, please
          add from selection </p>
    <% end %>

    <br>


    <div class="well">
      <div id="new_documents_added" class="hidden">
        <%= image_tag "error_red.png", class: "job-status-avatar" %>
        <b class="warning-text inline">Reresh page to see newly added documents</b>
        <p id="new_documents_added_names" class="push-right-small inline"></p>
        <br><br>
      </div>

      <%= form_for(PostJobReportDocument.new, :html => {:class => "inline"}, remote: true) do |f| %>
          <%= f.hidden_field :job_template_id, value: @job_template.id %>
          <%= f.select :document_id, options_for_select(@job_template.post_job_report_document_options),
                       {prompt: "Select a Document..."},
                       class: "tooltip-info custom-select custom-select-long",
                       "data-placement" => "bottom",
                       "data-title" => "Select from an document" %>

          <%= f.submit "Add to Post Job Report", class: "bluebtn btnsmall" %>
      <% end %>
    </div>

    <br><br>

    <div class="alert">
      <b>Post Job Report</b>

      <p>This list composes all the documents that will be merged once a job is closed.</p>
    </div>

  </div>
</div>

app/views/job_templates/_tray_tools.html.erb
<div class="tray hidden" data-tray="tools">
  <div class="page_header">
    <h1>Tools/Assets</h1>
  </div>

  <div class="">
    <div id="primary_tools_list">
      <% @job_template.primary_tools.includes(:tool).where(:template => true).order("tools.name ASC").each do |primary_tool| %>
          <%= render 'tools/primary/primary_tool', tool: primary_tool %>
      <% end %>
    </div>

    <% if @job_template.primary_tools.where(:template => true).count == 0 %>
        <p class="job-type-no-tools"><b>0 tools</b> - No tools added, please add from selection </p>
    <% end %>
    <br>

    <div class="well">
      <%= form_for(PrimaryTool.new, :html => {:class => "inline"}, remote: true) do |f| %>
          <%= f.hidden_field :job_template_id, value: @job_template.id %>
          <%= f.select :tool_id, options_for_select(@job_template.product_line.primary_tools.collect { |p| [p.name, p.id] }),
                       {prompt: "Select a Tool..."},
                       class: "tooltip-info custom-select custom-select-long",
                       "data-placement" => "bottom",
                       "data-title" => "Select from an existing primary tool on this product line" %>

          <%= f.submit "+ Add Tool to Job Type", class: "bluebtn btnsmall" %>
      <% end %>

      <div>
        <br><br>

        <p class="push-right-small">
          <b>No tools above or not the one you want?</b>
        </p>
        <br>

        <p class="push-right-small">Add it to the product line so you can add it to the job type...</p>
        <br><br>
        <%= link_to "+ Add New primary tool on product line", new_tool_path(:product_line => @job_template.product_line.id), remote: true,
                    class: "bluebtn btnsmall gray tooltip-info show-modal-button", id: "add_primary_tool",
                    "data-placement" => "bottom",
                    "data-title" => "Add primary tool to job type" %>
      </div>
    </div>
  </div>

  <br>

  <div class="content alert">
    <b>Primary Tools</b>

    <p>All tools that are required to compose the job system</p>
  </div>
</div>

app/views/job_templates/elephant_destroy.html.erb
<div class="error-page">
  <%= image_tag "blue_logo.png" %>

  <div class="message">
    <h1>Can't Delete Item</h1>

    <p>This item is being used in jobs, <br> please contact <%= link_to "Elephant Support", help_path, class: "blue-text" %> to delete this item.</p>
  </div>
</div>

app/views/job_templates/index.html.erb
<% provide(:title, I18n.t("job_templates.index.title")) %>

<div class="page_header">
  <h1><%= t "product_lines.index.title" %></h1>

  <h2><%= @product_lines.count %></h2>

  <%= link_to I18n.t("product_lines.index.new"), new_product_line_path, remote: true,
              class: "bluebtn page_header_button", id: "new_product_line_link" %>
</div>

   <div id="product_lines">
<%=  render @product_lines  %>
</div>

app/views/job_templates/new.html.erb
<div class="page_header">
  <h1><%= t ".title" %></h1>
</div>

<div class="form">
  <%= form_for(@job_template) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>


      <%= render 'fields', f: f %>

      <div class="actions">
        <%= f.submit I18n.t("job_templates.new.save"), class: "bluebtn pull-right form-loading-on-click" %>
      </div>

  <% end %>
</div>

<%= render "layouts/inline_loading", title: "Creating job type, please wait" %>

app/views/job_templates/show.js.erb
$('#job_description').empty();
$('#job_description').append('<h3><%= @job_template.name %></h3>');
$('#job_description').append('<%= @job_template.description %>');

app/views/job_templates/show_jobs.html.erb
<% provide(:title, 'Job System: ' + @job_template.name) %>

<div class="page_header">
  <h1><%= @job_template.name %></h1>

  <h3 class="inline">&nbsp;Job System</h3>

  <h2 class="paginated-count">Jobs:
    <%= render 'layouts/paged_header', items: @jobs %>
  </h2>

</div>

<% if !@is_paged %>
    <div class="well">
      <%= render 'jobs/index_parts/jobs_count', jobs: @job_template.jobs %>
    </div>
    <br>
<% end %>

<div id="jobs" class="list">
  <% @jobs.each do |job| %>
      <%= render 'jobs/job_progress_link', job: job %>
  <% end %>
</div>

<% if @is_paged %>
    <%= will_paginate @jobs %>
<% else %>
    <br>
    <div class="alert">
      <%= link_to "View all jobs active and closed (" + @job_template.jobs.count.to_s + ")", job_template_path(:page => "1"), class: "activity-user-link" %>
    </div>
    <% if @jobs.empty? %>
        <div class="no-alerts">
          <p class="center"><%= t ".no_jobs" %></p>
        </div>
    <% end %>
<% end %>